version: '3'

services:
  redis-primary:
    image: redis:latest
    command: redis-server --appendonly yes --maxmemory <max-memory> --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - /home/student/a2group02/redis-data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - redis-network

  python-redis-api:
    image: python-redis-api
    command: redis-server --replicaof redis-primary 6379 --maxmemory <max-memory> --maxmemory-policy allkeys-lru
    depends_on:
      - redis-primary
    deploy:
      placement:
          constraints: [node.role == worker]
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - redis-network

networks:
  redis-network:
    driver: overlay

volumes:
  /home/student/a2group02/redis-data:
    external: false
    