#!/bin/bash
# This script sets up a Redis cluster with hardcoded IP addresses

# Hardcoded IP addresses for the nodes
IP1="10.128.1.70"
IP2="10.128.2.70"
IP3="10.128.3.70"
IP4="10.128.4.70"

# ssh into primiary node and init docker swarm
ROLE=$1
JOIN_TOKEN=$2
PERSISTENT_STORAGE_PATH="/var/lib/redis"

# Loop through each IP and set up the redis cache node
if [ "$ROLE" = "init" ]; then
    docker build -t python-redis-api .
    docker swarm leave --force
    # Initialize the swarm on the manager node
    docker swarm init --advertise-addr "$IP1"

    # Create the persistent storage path
    mkdir -p "${PERSISTENT_STORAGE_PATH}"

    docker stack deploy -c redis-docker-compose.yml redis_stack


elif [ "$ROLE" = "join" ]; then
    # Join the swarm as a worker node
    for IP in $$IP2 $IP3 $IP4; do
        ssh student@IP "docker build -t python-redis-api .;docker swarm leave --force; docker swarm join --token "$JOIN_TOKEN" "$IP1":2377"
    done;

else
    echo "Unknown role: $ROLE"
    echo "Usage: $0 init <MANAGER-IP> | join <MANAGER-IP> <WORKER-JOIN-TOKEN>"
    exit 1
fi