#!/bin/bash

# Ensure the directory exists
mkdir -p ${PERSISTENT_STORAGE_PATH}

# Set the maximum memory you want Redis to use, for example "256mb"
MAX_MEMORY="256mb"

# Set the number of replica instances
REPLICA_COUNT=3

# Replace the placeholders in the docker-compose file
sed -i "s|<max-memory>|${MAX_MEMORY}|g" ../docker/docker-compose.yml

# Deploy the stack
docker stack deploy -c docker-compose.yml redis_stack

# Check the services
docker service ls