#!/bin/bash

# Hardcoded IP addresses for the nodes
IP1="10.128.1.70"
IP2="10.128.2.70"
IP3="10.128.3.70"
IP4="10.128.4.70"

# Loop through each hardcoded IP and stop/remove the Cassandra containers
for IP in $IP1 $IP2 $IP3 $IP4; do
    ssh student@$IP "docker swarm leave --force"
done