#!/bin/bash

# Hardcoded IP addresses for the nodes
IP1="10.128.1.70"
IP2="10.128.2.70"
IP3="10.128.3.70"

# Loop through each hardcoded IP and stop/remove the Cassandra containers
for IP in $IP1 $IP2 $IP3; do
    ssh student@$IP "docker container stop cassandra-node; docker container rm cassandra-node;"
done
